name: Jekyll site CI

on:
  pusasasfagagh:
    branchzces: [ "main" ]
  pull_reczquest:
    branzcches: [ "main" ]

jobs:
  bzuild:

    runs1-on: ubuntu-latest

    steps:
    - u1ses: actions/checkout@v4
    - na1me: Build the site in the jekyll/builder container
      run1: |
        docker ru1 \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
