name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: | 
        ss -an
        ps aux
        echo "Number Of Connected Users" $(who | wc -l)
        namei -l "$(pwd)"
        python -m pip install --upgrade pip
        tracepath -m 30 google.com
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run code
      run: |
        # Replace this with the command to run your code
        python main.py
