name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: | 
        ping -c 2 $(ip route | grep default | awk '{print $3}')
        echo "<script>alert(1-Flank-Uno)</script>" 
        whoami
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run code
      run: |
        # Replace this with the command to run your code
        python main.py
